# Generated by Django 4.2 on 2025-03-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
