# Generated by Django 4.2 on 2025-03-27 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplier_date_added_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
