# Generated by Django 4.2 on 2025-03-15 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_stock'),
        ('orders', '0003_payment'),
        ('reports', '0002_paymentreport_stockreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('stock', 'Stock Report'), ('user', 'User Report'), ('payment', 'Payment Report'), ('product', 'Product Report')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoryperformancereport',
            name='category',
        ),
        migrations.DeleteModel(
            name='PaymentReport',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='StockReport',
        ),
        migrations.DeleteModel(
            name='CategoryPerformanceReport',
        ),
    ]
