# Generated by Django 4.2 on 2025-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivered_at_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refund_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
